server:
  port: 8087
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/test-dev-environment
    username: hello
    password: hello
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
